AsteroidOS/asteroidos.org

- pages/wiki/building-asteroidos.hbs
- Added python2.7 to prerequisites
- Rearranged page so required programs are before clone/setup.
> Add python2.7 to prerequisites.

- pages/wiki/building-asteroidos.hbs
I cleaned the instructions up a bit and added instructions on how to build AsteroidOS in Docker.
> Add instructions to build in Docker

- pages/main/install.hbs
These changes introduce more active voice and slightly more brevity in the FAQ. They also address a couple grammatical errors and a misspelled word.
> Improve grammar and fix typo

- pages/wiki/bluetooth.hbs
I know, a bit late. But here is some information on how to pair with an audio device or HID device ;)
> Add information on how to pair to a Bluetooth Audio or HID device.

- pages/main/install.hbs
Adds "Telescope" + OpenStore link to the answer of "Where can I find a phone synchronization app?"
> adds "Telescope" to FAQ

- pages/install/dory.hbs
- pages/install/sparrow.hbs
- pages/install/sturgeon.hbs
- pages/wiki/porting-guide.hbs
This does not include how @hummlbach and I came up with a fix for sensors on sparrow. This should be done at a later stage.
The sensor information here was something I was stuck on for a long time while I was porting sturgeon.
> Add some more info on sensor issues and tilt-to-wake known state

- pages/main/install.hbs
- pages/wiki/porting-status.hbs
Straightforward stuff :)
Made a small mistake by just adding sturgeon at the bottom while the list of watches is in alphabetical order(wrt codenames).
Also noticed a small error where not all maintainers are not in italics.
> Styling fixes

- pages/install/lenok.hbs
As per https://github.com/AsteroidOS/meta-lenok-hybris/commit/e70cc4b1e68e445004901be7889c532188b94e81 the heart rate sensor and tilt-to-wake should work, courtesy of @LittleFox94.
> lenok: Mark hrm and tilt-to-wake as working.

- pages/install/sturgeon.hbs
Someone asked for that change in IRC, saw the question multiple times. Just make it clear on the website
> make clear Huawei Watch GT/GT2 is not supported

- pages/main/install.hbs
- templates/layouts/content.hbs
As discussed in https://github.com/AsteroidOS/asteroidos.org/issues/80
Also took the liberty to allow for markdown in content files :smile:
The watch stars is pretty much a copy of the current issue. Let me know if you agree with the current star rating. I based it on the current support matrix and the general support right now of the watches.
> install: Change watch ratings and reorder.

- pages/install/bass.hbs
Please let me know if the note makes sense. Not sure if it's entirely clear what I am trying to say here.
> bass: Add note about heart rate sensor.

- pages/wiki/building-asteroidos.md
This improves the consistency with the rest of the command and is also preferred by [BashFAQ](http://mywiki.wooledge.org/BashFAQ/082) and the [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xcu_chap02.html#tag_23_02_06_03).
> replaces backticks with $(...) for consistency

- pages/install/harmony.md
- pages/install/inharmony.md
- pages/install/lenok.md
- pages/install/tetra.md
Updates the watch support state. Please confirm that I didn't make false claims :wink:
> Update watch support state (sensors/aod)

- styles/bootstrap/code.less
> Remove nowrap from inline code blocks

- pages/wiki/emulator.md
In addition to the markdown conversion this commit adds required
parameters to the qemu command and adds a note about issues under x11
sessions.
> convert to md and improve instructions

- pages/install/tetra.md
- templates/layouts/aw-install-simg.hbs
Please merge after the real install images are published:
https://release.asteroidos.org/nightlies/tetra/asteroid-image-tetra.simg
> tetra: Update real install instructions

- pages/wiki/package-installation.md
Suggestion to include a short script usage description first to not give newcomers the impression the manual method is needed.
> added script usage to package-installation page

- pages/wiki/useful-commands.md
> added Timezone, date & time hint to useful-commands page

- pages/wiki/building-asteroidos.md
- pages/wiki/creating-an-asteroid-app.md
- Some mounts can be read-only
- Toolchain building with docker
> More docker usage doku

- pages/install/skipjack.md
Since Skipjack now supports bluetooth, add a check to that, plus adding some other stuff like GPS and NFC,
> Add more support options for skipjack and enable bluetooth

- pages/wiki/watchfaces-creation.md
As promised long ago, this is an extension of the watchface creation wiki to include all the findings we discussed in matrix chat and where found during creation of watchfaces over the last years.
Those where partly accumulated in the unofficial-watchfaces readme.md. Which this commit moves "here". https://github.com/eLtMosen/unofficial-watchfaces/commit/ee46a11f9cc030757ddaa14ec7a9768578bc3284
Detailed explanations of the script usage and some encouraging words to show how easy it actually is to get started, shall improve user and contributor flow into "self service" instead of coming to chat with redundant questions in light of possible 2.0 momentum.
Proof reading kindly supported by @beroset 
Any additional hints to include more details are very welcome.
> Update WF creation guide with script explanations

- pages/wiki/watchfaces-creation.md
Its final011-masterdraft05-thoughtToBeReleaseWorthy05 now.
I think these are the last necessary corrections from my side.
> Fix typos and fromat for better text flow

- pages/wiki/useful-commands.md
- templates/layouts/aw-install-simg.hbs
- templates/layouts/aw-install.hbs
And a warning about setting the timezone breaking time sync.
> Update wiki with info on how to access bootloader manually

- pages/wiki/porting-status.md
- pages/wiki/useful-commands.md
And also fix some small typos/other grammatical oddities.
> Provide `tetra` install link and document `invoker` usage.

- pages/wiki/documentation.md
Add IP Connection page to User section
Move Emulator from User to Dev section.
Sort Useful Commands page up to order SSH - > IP -> Update pages.
> [documentation.md] Sort wiki page entries

- pages/wiki/documentation.md
Fixing an error introduced in previous commit
> [documentation.md] Fix unintended line breaks from double spaces

- pages/wiki/building-asteroidos.md
Uses a chart to sort the different requirements
> Add Fedora requirements to building documentation

- pages/wiki/creating-an-asteroid-app.md
The CMAKE_PROGRAM_PATH variable was not set in the instructions and the result was that the generate_desktop CMake function would silently fail.  QtCreator also maddeningly refuses to allow the C and C++ compilers to be set to <No compiler> unless the Qt version (which is below those settings) is set to "None" first, so this was also documented. The troubleshooting section was added based on the recent experience of several new developers.
> Add an env variable and troubleshooting section

- pages/install/sparrow.md
Tested on sparrow after https://github.com/AsteroidOS/meta-smartwatch/pull/64
> Change Wifi and Audio support matrix color to good/green

- pages/install/narwhal.md
As of https://github.com/AsteroidOS/meta-smartwatch/pull/89 we now have a functional microphone on `narwhal`.
> narwhal: Microphone is now functional.

- pages/wiki/porting-guide.md
add @MagneFire - how to play and record audio
source: https://github.com/AsteroidOS/meta-sturgeon-hybris/pull/1
> Update porting-guide - test audio

- pages/watches-support.json
This is based on comments from docgalaxyblock on a previous PR,
https://github.com/AsteroidOS/asteroidos.org/pull/177
It adds compass to narwhal, tilt-to-wake on wren, and speaker to
sparrow.  It also change the heart rate sensor from unknown to good
based on a recent merged fix for sturgeon.
> Update watch status tables

- pages/wiki/openembedded.md
We need a quick start guide to understanding and using bitbake in the context of AsteroidOS beyond the existing "RTFM" advice
> add "working with bitbake" section

- package-lock.json
As described in
https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json, the package-lock.json file is intended to be checked into source control, in part to provide a deterministic and repeatable recipe for constructing the web site.  This complements https://github.com/AsteroidOS/asteroidos.org/pull/178
> Commit current version of package-lock.json

- pages/install/features.md
- styles/components/install-support-table.less
- templates/layouts/aw-install-multi.hbs
- templates/layouts/aw-install-simg.hbs
- templates/layouts/aw-install.hbs
- templates/layouts/beluga-install.hbs
- templates/layouts/featuretable.hbs
- templates/layouts/mooneye-install.hbs
- templates/layouts/mtk-install.hbs
> Add features legend

- pages/wiki/building-asteroidos.md
Add prerequisites for Arch Linux
> [building-asteroidos.md] Add Arch package install

- pages/all-features-template.json
- pages/watches-support.json
As mentioned in https://github.com/AsteroidOS/asteroidos.org/pull/222 this adds model information into the master json file as a first step in making it possible to programmatically present this data instead of hardcoding it.
> Add models to json

- pages/wiki/porting-status.md
> Fix links in porting-status unreleased ports

- pages/install/lenok.md
Analog to bass, like found by @GeckoEidechse 
This adresses:
- https://github.com/AsteroidOS/meta-smartwatch/issues/55
- https://github.com/AsteroidOS/meta-smartwatch/issues/159
- https://github.com/AsteroidOS/asteroidos.org/issues/238
> [Lenok] Add update hint to fix sensors

- pages/all-features-template.json
- pages/watches-support.json
This adds "soc", "kernelversion" and "androidversion" as three new fields in the json file.  The data was populated using some awk scripts against the meta-smartwatch git repository.  The data is not yet used, but will be useful for an upcoming PR to show hardware and software details for each watch.
> Add kernel versions

- pages/main/faq.md
This solves the clipping
But question is if the text is possibly too short now.
> Shorten headlines to make the menubar better legible and not clip

- pages/wiki/package-installation.md
- pages/wiki/watchfaces-creation.md
Since this PR was merged https://github.com/AsteroidOS/unofficial-watchfaces/pull/106 we needed to also modify the instructions on the website to correctly identify the name of the new unified script and to show its options and describe its operation.
> Unified script update

- pages/install/sparrow.md
- pages/watches-support.json
- templates/layouts/aw-install-dual.hbs
Remove wren from install page
And create aw-install-dual.hbs to work with dual system image but one install item watches
> Merge sparrow wren

- pages/wiki/package-installation.md
The newest version of the unofficial-watchfaces "watchface" script now has the ability to update itself from git.  This documents that change.  
**NOTE:** This depends on https://github.com/AsteroidOS/unofficial-watchfaces/pull/108 being merged.
> Update instructions to document "watchface update"

- styles/components/news.less
> Fix news-row width

- templates/layouts/beluga-install.hbs
This fixes https://github.com/AsteroidOS/asteroidos.org/issues/262
> Remove double Hardware Support header

- pages/main/faq.md
- templates/includes/faq-header.hbs
- templates/layouts/faq.hbs
Fixes https://github.com/AsteroidOS/asteroidos.org/issues/263
On page load now:
> Drop Header and change all markdown h2 to h1

- pages/watches/features.md
> Add last updated date as per hint from user aasami on matrix

- templates/includes/installbox.hbs
- templates/includes/watches-header.hbs
- Remove the codename from watches page title 
- Add space after commas
as per this discussion https://github.com/AsteroidOS/asteroidos.org/issues/343
fixes https://github.com/AsteroidOS/asteroidos.org/issues/329
> Remove codename from title

- pages/news/nightstand.md
Just as in the title, this fixes a few typos in the nightstand mode news article.
> Fix typos in nightstand article.

- package-lock.json
- templates/layouts/featuretable.hbs
In conversation with @eLtMosen, he suggested that it would be nice to have our stars ratings repeated in the features table.  This implements that suggestion.
> Add stars column to featuretable

- pages/watches/features.md
- templates/layouts/featuretable.hbs
> Add support stars to experimental watches

- pages/wiki/building-asteroidos.md
Capitalize "Linux" in the note if necessary.
> Added Alpine Linux package list

- pages/wiki/boot-process.md
Based on my own recent confusion, this clarifies the instructions for how to troubleshoot boot problems by providing exact commands and clarifying the context in which the commands are issued.
> Clarify boot troubleshooting advice

- pages/watches/firefish.md
- pages/watches/smelt.md
Thanks to @dodoradio for spotting this
Fixes: https://github.com/AsteroidOS/asteroidos.org/issues/370
> Remove advise to solder to the watch pads

- templates/layouts/aw-install.hbs
- templates/layouts/mtk-install.hbs
- Fixes https://github.com/AsteroidOS/asteroidos.org/issues/373
> [Hardware Support table] Add advise to test HW features pre install

- pages/watches/beluga.md
- Fixes https://github.com/AsteroidOS/asteroidos.org/issues/376
> [Beluga Install] Add advise to update firmware

- pages/watches-support.json
- pages/watches/features.md
- Change GPS to good on pike
- Bump last updated section date
- Add spacing to footer
> [Features table] Update pike and bump last-updated date

- pages/watches-support.json
hoki has a speaker, but it looks like the feature entry for it may have been missed
> watches: add speaker entry for hoki

- templates/layouts/aw-install.hbs
- templates/layouts/mtk-install.hbs
To increase exposure of the wiki add a link to it as a post installation step.
> Add link to the wiki as a post install read.

- pages/watches-support.json
- https://github.com/AsteroidOS/meta-smartwatch/pull/209: Fixes USB for `sawfish`.
- https://github.com/AsteroidOS/meta-smartwatch/pull/211: Fixes WLAN for `skipjack` and `swift` (but was already marked good).
> sawfish,skipjack: Update support status.

- pages/watches-support.json
* fixes https://github.com/AsteroidOS/meta-smartwatch/issues/225
> beluga: fix codenames

- pages/watches/features.md
- templates/layouts/watches.hbs
This patch fixes both #412 and #413.
> Clarify experimental

- pages/watches/beluga.md
Add OPPO Watch X is not supported to beluga.md
OPPO Watch X is not same OPPO Watch.
> Add OPPO Watch X is not supported to beluga.md

- templates/includes/install-prepare-adb.hbs
As requested by @xuid0 in this issue https://github.com/AsteroidOS/meta-smartwatch/issues/256
Update the windows platform tools download to the official google archive
> Update platformtools link to latest google archive
