- pages/wiki/bluetooth.hbs
The second configuration file that needs to be changed, `asteroid/src/meta-asteroid/recipes-connectivity/bluez5/bluez5/main.conf`, was incorrectly referenced in the guide with a duplicate `src` in the path. Super small typo, but figured it was a path and worthy of fixing in the real documentation.
> Fixed typo in path for 2nd configuration change

- pages/wiki/porting-status.hbs
There is [this thread](https://forum.xda-developers.com/moto-360-2015/help/help-finding-pin-t3260871/page3) about the Moto 360 pinout.
I successfully connected it to a PC, booted the watch into Fastboot and dmesg showed this:
```
[  662.633549] usb 2-1.2: new high-speed USB device number 10 using ehci-pci
[  662.732596] usb 2-1.2: New USB device found, idVendor=22b8, idProduct=2e80
[  662.732603] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  662.732607] usb 2-1.2: Product: Fastboot smelt NS
[  662.732610] usb 2-1.2: Manufacturer: Motorola Inc.
[  662.732613] usb 2-1.2: SerialNumber: <manually removed>
```
I haven't tried to access fastboot or boot AsteroidOS as I broke my screen cable in the process of dissasembling the watch. Turns out only the bottom case needs …
> Move Moto360 2nd gen and Sport to 'possible ports not supported yet'

- templates/includes/javascripts.hbs
Follow up of #20 
This commit removes the leftovers of the google-analytics.com integration, which has been removed in commit 7e470818df2e0e8e7441d8797d63f8304729a6fe
> Removed leftovers of google-analytics.com integration.

- pages/wiki/porting-status.hbs
All the changed watches are the same device called "bluegill" by Compal. When opened up they have the required pinouts.
> Correction

- pages/wiki/creating-an-asteroid-app.hbs
I think this was the only remaining occurrence of a '.' that could be replaced by 'source'.
> Replace '.' with 'source' to improve consistency

- styles/bootstrap/code.less
Suggestion to have scrollbars in code tags with very long lines.
So ithat they would appear like this:
Instead of like this:
What do you think?
> Make code elements with lines longer than the width scrollable

- styles/components/main-nav.less
Logo in header had 0 left margin and it looked weird. I set this margin to 15px, because hamburger on right also has 15px and entire `.container` has 15px horizontal margin.
Screenshot before:
Screenshot after:
> Fix logo margin on mobile

- pages/wiki/porting-status.hbs
The 'PineTime' gets a lot of porting requests and does not meet the hardware requirements. This PR clarifies the state in our public documentation.
> Adds 'PineTime' to the impossible ports

- pages/wiki/porting-status.hbs
As per https://github.com/AsteroidOS/asteroid/issues/121 we now know that the GT versions don't have the hardware to properly support Linux.
> porting-status: Move Huawei GT/2 to impossible unmet hardware.

- pages/wiki/porting-guide.hbs
On recent builds we don't actually have a lipstick process. Replace this with asteroid-launcher.
Add some more information about how sensors work on smartwatches.
Add GitHub to place to help with troubleshooting.
One thing that may need changing is to move the added paragraph in the sensors section to the top of that section. Please let me know what you think of it.
> porting-guide: Update with recent findings.

- pages/install/anthias.hbs
- pages/install/bass.hbs
- pages/install/dory.hbs
- pages/install/harmony.hbs
- pages/install/inharmony.hbs
- pages/install/lenok.hbs
- pages/install/mooneye.hbs
- pages/install/smelt.hbs
- pages/install/sparrow.hbs
- pages/install/sprat.hbs
- pages/install/sturgeon.hbs
- pages/install/swift.hbs
- pages/install/tetra.hbs
- pages/install/wren.hbs
- styles/components/install-support-table.less
- styles/index.less
This PR changes the support table such that it wraps to the next row when it overflows.
Here is a comparison of what it looked like and what it looks like after the PR. Top one is the new implementation the bottom one is the old table.
Here are two images of what it looks like when the screen is too narrow:
Also I added a another color to indicate that the status of something is unknown:
> install: Wrap support row when screen is too narrow.

- Gruntfile.js
I was checking #89 on a clean copy of the master branch to check for any breaking changes and noticed that it doesn't generate HTML files at all.
This commit adds the markdown file extension (`.md`) to the source file regex in the Gruntfile.
> enables markdown in the Gruntfile

- pages/wiki/building-asteroidos.md
Fixes some formatting issues with the <code> sections.
https://github.com/AsteroidOS/asteroid/issues/141 mentioned some issues with the https://asteroidos.org/wiki/building-asteroidos/ page. Turns out that when we changed everything to markdown, this page broke. Here is a corrected one, by converting the page entirely to markdown.
Preview of what is is now vs what it was (i.e. broken)
> building-asteroidos: Changing styling to markdown.

- pages/wiki/creating-an-asteroid-app.md
Thank you @MagneFire for your help. Pretty sure i would have spent many more hours if i did not had your help.
The user for running selfmade qt applications has to  be ceres. Root will not work.
> User used for app development has to be ceres

- pages/wiki/openembedded.md
Previously pointing to 2.0; we're using 3.2 (gatesgarth) currently. This link points to the latest version of the docs. Also, I pointed it to an index rather than to the Mega-Manual page; the mega-manual definitely has its uses but it's a bit cumbersome to read. It's linked from the index, so still fairly easy to find.
> Update Yocto docs link

- pages/wiki/creating-an-asteroid-app.md
This PR finally addresses the lack of correct documentation for the new SDK that switches from `qmake` to `CMake`.
> Adapt SDK instructions for CMake.

- pages/install/skipjack.md
- pages/main/install.md
To be merged after https://github.com/AsteroidOS/meta-skipjack-hybris/pull/11 is merged, this PR adds Sensor Support where it counts, both in the Heart Rate Monitor and Tilt-To-Wake sensor, although Skipjack does not have a compass (Sad).
Also seems fitting based on the amount of supported hardware devices to bump Skipjack from two stars to three stars.
> Add Sensor Support And Add Star To Skipjack

- templates/layouts/aw-install-simg.hbs
- templates/layouts/aw-install.hbs
- templates/layouts/mooneye-install.hbs
As made aware by user silentnoodlemaster on matrix by trying to make a degooglified phone work with the installing WearOS only to unlock the bootloader.
It would be advised to make users aware of the manual methods to access the bootloader.
> Explain that ADB is not the only option to access the bootloader

- pages/wiki/ip-connection.md
- pages/wiki/ssh.md
- pages/wiki/update-asteroidos.md
As hinted by user coolguest25 on matrix. 
Adding wifi instructions since most watches with wifi capability have it supported in the meanwhile.
> Move IP connectivity logic to a separate page

- pages/wiki/package-installation.md
- pages/wiki/ssh.md
In [this recent commit](https://github.com/AsteroidOS/unofficial-watchfaces/commit/dccef7ca9a33d34cef589067dbbc91876b928c9b) the directory structure for watchfaces and wallpaper was changed.  This is the corresponding fix for the documentation describing how to manually install watchfaces and wallpapers.
> fix directory paths to match recent changes

- pages/install/sturgeon.md
It seems that there are GT3 and GT runner variants now, they are not compatible with sturgeon.
> sturgeon: Mention all GT variants and link to the porting status page.

- pages/install/catfish.md
- pages/install/firefish.md
- pages/install/ray.md
- pages/install/smelt.md
- pages/main/install.md
- templates/layouts/aw-install.hbs
Adds more details to the individual installation pages as a follow-up to https://github.com/AsteroidOS/asteroidos.org/pull/152.
Additionally, this uses a custom template for `carp/smelt` to refer to different drivers for Windows as the universal ones don't seem to work. This was reported by @docgalaxyblock (Thanks!)
> More installation details & installation fix for carp/smelt on Windows

- pages/install/catfish.md
- pages/install/firefish.md
- pages/install/ray.md
- pages/install/skipjack.md
- pages/install/smelt.md
- pages/main/install.md
- templates/includes/install-header.hbs
- templates/layouts/aw-install-simg.hbs
- templates/layouts/aw-install.hbs
- templates/layouts/beluga-install.hbs
- templates/layouts/mooneye-install.hbs
- templates/layouts/mtk-install.hbs
This PR includes some minor changes.
It consists of renaming the `repo` to `label` as all watch repos have been merged some time ago and `repo` was mis-used for `label`s.
Additionally, it uses the `label` in the header to indicate the compatibility with the different watches.
Adding to that, a bit more detail is added to the page header when it comes to the specific watch.
This fixes https://github.com/AsteroidOS/asteroidos.org/issues/159 and addresses the comment in https://github.com/AsteroidOS/asteroidos.org/pull/158.
Previews:
> Use labels, add codenames to header & add tunny to compatiblitity

- README.md
- pages/wiki/documentation.md
- pages/wiki/localweb.md
This adds documentation to the web pages for the containerization implemented in https://github.com/AsteroidOS/asteroidos.org/pull/174 
They are technically independent, because they do not modify any of the same files, but it would make more sense to accept this one after #174 is merged.
> Add container docs

- pages/install/sturgeon.md
Since issue #82 is now fixed and closed, the warning about the heartrate
monitor not working on sturgeon is now obsolete.  This patch removes
that warning.
> Remove obsolete sturgeon heartrate monitor warning

- pages/watches-support.json
- pages/wiki/porting-status.md
This is the final consolidation of watch info for #176 which adds the list of maintainers to the json file and restructures the porting status page to use data from the json file rather than duplicating it.
> Maintainers to json

- pages/wiki/update-asteroidos.md
It's common for users to report a problem trying to update with opkg
that is a result of not having the correct date and time set on the
watch before using opkg so that the watch can validate the SSL peer
certificate of the server.  This adds that note to the instructions and
also shows the error message that results if one fails to follow them.
> Tell users to set time before using opkg

- pages/watches-support.json
This updates the AoD status for most of the watches with sprat being
marked as `unknown` per a conversation on Matrix.
> Update Always-On-Display status for most watches

- pages/wiki/porting-status.md
On the porting-status page, when maintainers are listed, they are listed with no space between the names; there is only a comma.  This adds a space after each comma to make the list easier to read and more pleasing in layout.  Suggested by DocGalaxyBlock on matrix chat.
> Add some spaces when printing the maintainers list

- styles/components/install-support-table.less
The currently supported status categories for watch features are "good", "bad", "unknown", and "na", but a discussion on matrix had multiple people asking about the possibility of a "partial" status.  This changes the yellow-orange color previously used for "unknown" to signify "partial" and uses a blue color for "unknown".
> Add support for "partial" as a status

- templates/layouts/featuretable.hbs
https://github.com/AsteroidOS/asteroidos.org/pull/191 has merged similar watches into a single page. This meant that the old pages are no longer valid and from now on they should refer to the merged page.
This fixes the issue where https://asteroidos.org/install/features/ would still link to `wren` and `ray` pages even though they are no longer valid.
This bug was reported by @docgalaxyblock
> featurelist: Fix issue where unified watches would link to old install pages.

- pages/wiki/porting-status.md
https://github.com/AsteroidOS/asteroidos.org/pull/191 has merged similar watches into a single install page.
This meant that the old pages are no longer valid and from now on they should refer to the merged page.
This bug was reported by @docgalaxyblock (Thank you for doing so :+1: )
> porting-status: Fix issue where unified watches would link to old install pages.

- pages/main/install.md
Hello! I found the features table link in https://asteroidos.org/install/ that It's not working because It has wrong tag.
> Fixed wrong link tag

- pages/wiki/emulator.md
This fixes a typo, adds some specifics relevant to newer versions of QEMU (that is, we now treat new versions as the norm and old versions as the exception) and removes a TODO note that points to a dead link.
> Update emulator instructions

- pages/watches-support.json
Updates the install page of `dory` to include @MagneFire's [improvements](https://github.com/AsteroidOS/meta-smartwatch/pull/148):
- tilt-to-wake
- adds @MagneFire as a maintainer
- increases dory to 4 stars (previously 3)
> Update dory's page

- pages/wiki/ble-profiles.md
This clarifies a number of things in the Bluetooth LE profiles page.
1. it changes to MD format rather than HTML to make it simpler to edit
2. it corrects and expands the Time Service explanation
3. it corrects and expands the Weather Service explanation and adds examples
> Clarify bluetooth

- pages/wiki/creating-an-asteroid-app.md
PR for [this](https://github.com/AsteroidOS/asteroidos.org/issues/125) issue.
> Update creating-an-asteroid-app.md for more indepth information for app development

- pages/wiki/localweb.md
- pages/wiki/package-installation.md
This fixes some typos and formatting, and adds an explanation of how to install community packages using `opkg`.
> Explain package system

- pages/install/anthias.md
- pages/install/bass.md
- pages/install/beluga.md
- pages/install/catfish.md
- pages/install/dory.md
- pages/install/firefish.md
- pages/install/lenok.md
- pages/install/mooneye.md
- pages/install/narwhal.md
- pages/install/sawfish.md
- pages/install/skipjack.md
- pages/install/smelt.md
- pages/install/sparrow.md
- pages/install/sprat.md
- pages/install/swift.md
- pages/install/tetra.md
- pages/watches-support.json
This PR aims to integrate the model numbers for most of the watches to their install pages, like noted in this issue:
https://github.com/AsteroidOS/asteroidos.org/issues/193
All model numbers have been researched to be correct. Multiple sources per search for each code where easily verifiable.
The advantage of listing the model numbers are:
- Users can better identify and verify the system image for the watch they are owning.
- Purchases on second hand market often yield much better results when adding the model number.
- Search engines will index the model numbers and list us in searches accordingly.
This PR also fixes the narwhal wlan feature matrix to "bad".
And adds E2 tunny to the install main page and feature matrix name for skipjack.
Currently model numbers for following watches …
> [Install pages ]Add all known model numbers and polish install pages

- pages/install/firefish.md
- pages/watches-support.json
Found an italian source with all DW6xx and DW7xx models listed. Updated the firefish/ray model numbers.
https://orologismartwatch.com/fossil-dw6-platform
https://orologismartwatch.com/fossil-dw7-platform
Also found that W1 is used a lot for sturgeon.
> Add info fix typo

- pages/main/faq.md
The FAQ section is now linked from the start page using the "Learn more" button.
Imo, thus the faq sections purpose has shifted from trying to firstly clear up misconceptions (and fence off buggy questions), to advertise our work and explain new users what they can expect.
To achive this:
- Move the apps and features section up and reformulated them into lists and added missing features.
- Move the "Playstore question" section right below the actual included apps section
- Move the sync client section up, above the "Differences to android" tirade.
- Add a user centric explanatory sentence to first section
- Streamline differences to wearos text.
Visually:
> Rework FAQ

- templates/layouts/aw-install-multi.hbs
- templates/layouts/aw-install-simg.hbs
- templates/layouts/aw-install.hbs
- templates/layouts/beluga-install.hbs
- templates/layouts/main-install.hbs
- templates/layouts/mooneye-install.hbs
- templates/layouts/mtk-install.hbs
The main install page now asks to make sure to be familiar with the FAQ before installing. 
Making the individual sentences on each install page redundant.
> Adapt install page text to recent move of the install FAQ

- pages/wiki/synchronization-clients.md
In particular how they can be used to connect a watch running AsteroidOS to an iOS device.
I came across [nRF Connect](https://apps.apple.com/gb/app/nrf-connect-for-mobile/id1054362403) while checking the [PineTime wiki](https://wiki.pine64.org/wiki/PineTime_FAQ#How_do_I_set_the_time_on_PineTime?) and found it also works with my lenok running AsteroidOS. I don't have other watches so I cannot confirm whether it works on all devices running AsteroidOS.
This is also by no means a replacement for a proper sync client but certainly better than no sync at all :P
(Now if someone could just fork [InfiniLink](https://github.com/InfiniTimeOrg/InfiniLink) and adapt it for AsteroidOS so that we have a proper sync client on iOS, that would be great x_x)
> Add note about generic iOS BLE apps

- pages/wiki/porting-status.md
Due to addition of pike to the supported watches, this removes it from the unreleased section on the porting status page.
> Remove pike from unreleased section

- pages/watches-support.json
Due to recent addition of many more firefish and ray models, the skagen falster 2 name for ray became unfitting.
Renaming to the main differentiationg factor, the casing size.
> Rename firefish and ray to Fossil Gen 4 46mm and 41mm

- pages/all-features-template.json
- pages/watches-support.json
As brought up by @docgalaxyblock and discussed with @MagneFire 
This PR adds "Crown" as a feature to watches that got the hardware to make the feature more easily discoverable and document it properly.
> Add crown to feature matrix and feature table of supported watches

- styles/components/news.less
- templates/layouts/news.hbs
This caused the nav-bar to be wider than the viewport
Before, toggling visibility: hidden and width
https://user-images.githubusercontent.com/15074193/222557284-d920e6fe-63d8-4f52-a80c-d428e80ac9d7.mp4
After setting display: none to the image
> Fix news-img item to not occupy space when hidden

- styles/components/install-box.less
- templates/includes/installbox.hbs
- Main goal is to fix the huge watch images when the page is viewed on phones.
- Now we got 
5 columns on wider than 1200px screens
4 columns at wider than 992px
3 columns up to 768px
2 columns from 480px
1 column below 480px, that one only at 60% width so the image is not blown up like before
- The table is now centered better than before, best to observe when focusing on the right edge alignment to the outer most menu item "contact". 
Before:
https://user-images.githubusercontent.com/15074193/222521340-b557b103-5403-4d09-b981-e7152af885a6.mp4
After
https://user-images.githubusercontent.com/15074193/222521389-c2d9fe33-664b-494f-965c-d3d1316222fc.mp4
View on a typical modern phone according to chromium:
https://user-images.githubusercontent.com/15074193/222521537-bfb13f1b-ef5d-4196-85bf-a7 …
> Redesign install main page colums

- styles/components/install-support-table.less
- templates/includes/install-header.hbs
The features table did wrap unfortunate on mobile devices.
This PR
- Makes the support-column width depend on viewport width
- Limits the minimum columns size to 15px where it was 25px before
- Removes the support-row wrap, introducing horizontal scroll on width lower than 600px.
- Sets a max-width of 1024px for the support-row so it does not get wider than the top menu
Downsides 
- The columns are rectangles, not squares anymore.
- This is hardcoded to 3.5VW and needs to be lowered in case more columns get added
Before, reported by @thorgalix21 on matrix:
Behaviour with PR implemented:
https://user-images.githubusercontent.com/15074193/222314645-da10b5e6-f40d-431d-8ced-265b75f08f79.mp4
> Make features table responsive

- styles/variables.less
> Change odd/even highlight to a more AsteroidOSish orange

- templates/layouts/aw-install-dual.hbs
- templates/layouts/aw-install-multi.hbs
- templates/layouts/aw-install-simg.hbs
- templates/layouts/aw-install.hbs
- templates/layouts/beluga-install.hbs
- templates/layouts/mooneye-install.hbs
It was noted in the matrix chat that the download source seemed a bit questionable.
In addition, some users reported that it is not working with latest windows versions.
- Link to the Google Developer page containing a ZIP at https://developer.android.com/studio/run/win-usb
- Direct link to the file is not possible
- Open link in new tab/window (browser setting) to not loose the install page scroll state
- Announce the new tab/window using the `title` feature to show a hint on mouse hover.
This fixes https://github.com/AsteroidOS/asteroidos.org/issues/203
Visually:
> Remove Clockwork mod USB driver and add Google USB driver

- templates/includes/nav-main.hbs
After discussion on matrix, this PR reorders the navbar items.
Goal was to move FAQ before Documentation. And proudly feature the Watches page.
> Reorder navbar items to present watches and FAQ page more obvious

- pages/watches/features.md
- styles/components/install-support-table.less
Fixed
- The the rotated class did not scale to the same width like the support-col. Driving the headers off center
- Legend support-col was too low min-width and looked too narrow
> [Featuretable] Fix legend and header flow

- templates/includes/popover-source-link.hbs
This fixes issue #271 by correctly constructing the link to the github source page no matter where in the hierarchy the page exists.
> Fix edit pen github link

- templates/includes/install-unlock-adb-beluga.hbs
- templates/includes/install-unlock-adb-round.hbs
Following the move of the instructions into an include block, this PR polishes and restructures the instruction steps to be even clearer.
- Add step 1.3 and 1.4 to explain every actual step the user has to take in detail and be able to reference it in chat. And make the steps more obvious by thus giving all of them a `<h3>` header.
- Add prominent hint that the unlock procedure will factory reset the device and the warranty might void..
- Add anchor and link to "skip to step 1.3" for users familiar with the manual methods. The anchor needs to be placed one line above the actual anchor target to account for the menu navbar.
- Reformulate much of the text for better flow
- Shorten 1.1 to "1.1 Enable ADB on your watch", omitting the "with the following steps:"
- Remove `.` and `:` from …
> Restructure ADB unlock steps

- templates/includes/head.hbs
According to @jrtberlin on matrix "We don't have a service under that subdomain. We can remove all references to the analytics stuff"
> Remove piwik analytics stuff from head

- pages/wiki/backup.md
- pages/wiki/documentation.md
Draft that has
- Manual backup instructions using adb and ssh
And misses:
- Srcipted method describing berosets host-tools
- Restore involving magenfires partition extraction script
> Add backup instructions

- pages/wiki/update-asteroidos.md
Explain/link to new install pages instead
> Remove reflash instructions from upgrade page

- pages/wiki/documentation.md
- pages/wiki/package-installation.md
- Move Bluetooth to developers since it clearly says "Technical details..."
- Sort developer porting related topics in row
- Move conferences down since its unrelated to other topics
- Rename Manual Watchface and Package installation to just Watchface and Package installation
- Sort Users topics by priority new users seeking general information would expect after having read the FAQ
New layout:
> Reorder and streamline topics

- styles/components/install-box.less
This ensures that there's enough space available such that there's no empty space on the right on the watches page.
Here's a before and after of the phenomenon.
> watches: Reduce width on smaller screen widths.

- pages/wiki/backup.md
- pages/wiki/useful-commands.md
- pages/wiki/watchfaces-creation.md
- templates/includes/install-temp.hbs
- templates/includes/install-unlock-adb-beluga.hbs
- templates/includes/install-unlock-adb-round.hbs
And unify ADB Mode, Developer options and ADB debugging
Fixes https://github.com/AsteroidOS/asteroid-settings/issues/65
Needs to be merged in sync with to be created PR in asteroid-settings to actually rename from Developer mode and add translation string for SSH Mode.
> Rename Developer Mode to SSH Mode

- styles/components/install-support-table.less
This fixes #349 by slightly enlarging the width of the name column to accomodate inharmony, which is currently the longest name.
> Fix featuretable alignment

- templates/includes/documentation-header.hbs
- templates/includes/news-header.hbs
- templates/includes/watches-header.hbs
Fixes https://github.com/AsteroidOS/asteroidos.org/issues/343 by swapping the svg slug for unicode char U+27E9.
> Add unicode slug to watches, news and documentation header

- pages/main/faq.md
Trying to solve this issue https://github.com/AsteroidOS/asteroidos.org/issues/240 now since weeks, i came to the realization that it would involve to mess with bootstrap. Since the sidebar handling and thus buggy addition of the `top:` parameter that should prevent the sidebar from overlapping with the footer is a bootstrap thing.
This PR aims to sort the entries into sub headings to work around this issue. By using the sidebar like intended, with sub categories shortening the sidebar height and thus prevent it to break at the footer.
We can sense-fully sort the entries like this imho since the resulting categories would then thematically fit the sub heading entries.
- What is AsteroidOS 
- Is Asteroid OS based on Android
- Can my watch run AsteroidOS
- Question not answered
This is how …
> [FAQ] Sort entries into sub categories

- pages/wiki/creating-an-asteroid-app.md
This fixes https://github.com/AsteroidOS/asteroid-settings/issues/80 by adding a language translation hint to the tips and tricks section of the "creating an AsteroidOS app" page.  It also enhances the command line build script in that same section.
> Translate hint

- pages/watches-support.json
This adds more detail to the SOC versions for MSM variants, specifically naming either msm8909 or msm8226 based on the CONFIG_ARCH_MSM8xxx=y line in each watch kernel's defconfig.
This fixes https://github.com/AsteroidOS/asteroidos.org/issues/366
> Add more detailed info on MSM SOC

- pages/wiki/creating-an-asteroid-app.md
- pages/wiki/useful-commands.md
As @PureTryOut has correctly noted, "booster-qtcomponents-qt5 has been deprecated upstream and the application launches fine with just booster-qt5 as well."
This adjusts our instructions to use booster-qt5 instead.
> Update instructions to use booster-qt5

- pages/watches-support.json
Magnefire and I just got WLAN and hands working on narwhal. Hence:
- mark WLAN as 'working', recently fixed
- mark hands as 'partial', as hands-timesync now sets correct time and timezone to hands
since everything but hands is now green (and since hands are 'partial' rather than 'bad') it seems appropriate to bump narwhal to 4 stars.
> narwhal: add new features and upgrade to 4 stars

- pages/watches-support.json
Wren, just like its sibling sparrow, is a msm8226 device.
> Correct soc value for wren

- pages/watches-support.json
- pages/watches/koi.md
This marks koi as experimental and adds a warning about bricking issues 
my ayu just bricked itself, and I believe it is prudent to mark experimental until we figure out how fatal this is.
This is really really really disappointing.
> Koi: mark as experimental due to bricking issues

- templates/layouts/watches.hbs
- Add hardcoded line breaks as spacing to footer. Using a template has been investigated but no universal solution was found.
> [Watches page] Add spacing to footer

- pages/wiki/useful-commands.md
- The issue of setting a timezone breaking time sync with AsteroidOSSync is now solved. As confirmed and tested by user cambionn and myself on 2 more watches.
> [Useful commands / Timezone setting] Remove warning

- pages/wiki/ip-connection.md
This clarifies and expands the IP over USB description to better explain what is required, how it works, and how to adapt to possible different configurations and was prompted by comments on matrix from several users who had had difficulty with the existing instructions.
> Add clarifications to the IP over USB section

- pages/wiki/useful-commands.md
- Tested again, only pressing the front button also seems to work, but just holding both buttons went more reliable when rebooting via the power button.
> [Fastboot combo] Add pike manual method

- pages/wiki/building-asteroidos.md
- The hint to not only run the prepare-build.sh but source it made the codeblock look confusing
- Double-click selection of the whole line contained the comment/hint.
- Moved over the codeblock
- Added important note to highlight it.
> [Building asteroidos] Move source hint from codeblock

- pages/wiki/creating-an-asteroid-app.md
- The hint to source made the codeblock look confusing
- Double-click selection of the whole line contained the comment/hint.
- Moved over the codeblock
- The sentence broke at the comma and started off with a capital letter. .
> [Creating an app] Move source hint from codeblock

- templates/layouts/aw-install.hbs
- templates/layouts/mtk-install.hbs
- Add hardcoded line breaks as spacing to footer. 
- Using a template has been investigated but no universal solution was found. 
- Fixes https://github.com/AsteroidOS/asteroidos.org/issues/297
> [Install pages] Add spacing to footer

- templates/includes/install-full-adb-push-ext4.hbs
- templates/includes/install-full.hbs
- templates/includes/install-prepare-adb.hbs
- templates/includes/install-temp-encrypted.hbs
- templates/includes/install-temp-flash-boot-to-recovery.hbs
- templates/includes/install-temp.hbs
- templates/includes/install-unlock-adb-beluga.hbs
- templates/includes/install-unlock-adb-round.hbs
- templates/includes/javascripts.hbs
- Remove the necessity to target IDs but find the closest install-code-wrapper class, find the code block in that and copy its content to clipboard.
- Remove redundant IDs from install pages code blocks since the copy to clipboard function does not rely on those anymore.
Signed-off-by: Timo Könnecke koennecke@mosushi.de"
> [Copy to clipboard button] Make function more universal 

- pages/watches-support.json
- templates/layouts/aw-install.hbs
- templates/layouts/mtk-install.hbs
The idea being that one can inform themselves prior to installing AsteroidOS.
The only page that doesn't exist at the time of writing is the wiki page to `harmony/inharmony`.
| | |
|-|-|
| ![image](https://github.com/AsteroidOS/asteroidos.org/assets/7857908/3bd8f279-52be-4762-a12b-c0fc521d2bf3)|![image](https://github.com/AsteroidOS/asteroidos.org/assets/7857908/45d7f629-5a8d-41e8-b2f8-dfe7d14f4e97)|
> Add link to watch specific page.

- templates/includes/install-unlock-adb-beluga.hbs
- templates/includes/install-unlock-adb-round.hbs
- Make clear in the info box to not relock the bootloader while AsteroidOS is installed
- Extend first sentence by <and booting> to make clear that AsteroidOS always needs an unlocked BL
> [unlock] Warn to not relock

- pages/main/contact.md
We use a bridge to allow Libera.Chat users to talk to Matrix users. A web IRC client is used to achieve this. Recently the bridge was temporarily disabled [^1] rendering the web IRC client useless.
[^1]: https://libera.chat/news/matrix-bridge-disabled-retrospective
> contact: Disable IRC webclient.

- styles/components/install-preparation-box.less
- templates/includes/install-prepare-adb.hbs
- Add zypper command for OpenSuse (as spotted by user Nerdius in the Matrix-Chat) and move it to a new code-line
- Make install-preparation-box same height for downloads and install
> [install-preparation-box] Add zypper and fix height

- templates/includes/install-temp-encrypted.hbs
This adds a missing step after the the asteroidos.ext4 file is pushed. When the file is pushed one should reboot again to successfully boot into AsteroidOS.
This fixes https://github.com/AsteroidOS/asteroid/issues/255.
This is what the install page looks like after this change:
> install: beluga: Add reboot step after pushing the .ext4 file.

- pages/watches-support.json
* fixes https://github.com/AsteroidOS/meta-smartwatch/issues/228
> beluga: mark NFC support as "partial"; explain why USB support is "partial"

- Dockerfile
This specifies a particular version for the Alpine image rather than using "latest".  This is better both because it causes the created image to be repeatable (that is, no matter when we build, it's always the same result) and also gets around a bug described here: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/58154
> Add specific version for alpine image

- templates/_plugins/rss.js
Previously the RSS feed was generated for every assembled page resulting in a `feed.xml` in every sub-directory.
Moreover it also resulted in wrong links to the news pages (omitting `news` in the url).
> rss: Only generate feed when assembling main page.

- styles/components/callout.less
- templates/includes/install-unlock-adb-beluga.hbs
- templates/includes/install-unlock-adb-round.hbs
As hinted by NickTheNeko on Matrix, the only recently added DO NOT relock warning was not obvious since hidden in the Notes box.
- Move the relock warning to its own callout-danger box
- Adjust the callout-danger color scheme to be more intense red.
After change:
> Make DO NOT relock warning more obvious

- pages/watches/catfish.md
As noted by hacker420 in the matrix chat, an explanation to why GPS and LCD are listed as partially supported might be good for clarity.
After the change:
> [catfish] Add info notes for GPS and LCD support

- templates/includes/install-full-adb-push-ext4.hbs
- templates/includes/install-full.hbs
- templates/includes/install-prepare-downloads.hbs
- templates/includes/install-temp-encrypted.hbs
- templates/includes/install-temp-flash-boot-to-recovery.hbs
- templates/includes/install-temp.hbs
- templates/layouts/mtk-install.hbs
Renames asteroid-image-<device>.ext4 to asteroid-image-<device>.rootfs.ext4
Currently a build of our current Yocto scarthgap is running. I'll test this PR once the build is finished and merge once confirmed working correctly.
> templates: Rename rootfs image to new Yocto scarthgap based format

- pages/watches/pike.md
This is a result of the findings in https://github.com/AsteroidOS/meta-smartwatch/pull/238
> watches: Use sparse image instructions for pike

- styles/components/about-rows.less
This updates the slide show animation (for the screen images at the top of the main page) to use animation which is now supported by all browsers, rather than the deprecated -webkit-animation.
It also changes the animation so that it goes forward and then reverses rather than its current behavior of resetting quickly to the beginning.
> Use css animation, not obsolete -webkit-animation

- pages/main/index.md
This appears to have been introduced in https://github.com/AsteroidOS/asteroidos.org/commit/da5eebef3b8c5f8c0358383b807ec9403f75e4f3.
> main: Fix typo in Freedom & Privacy text

- pages/watches/mooneye.md
This relies on the use of sparse images.
Currently draft as the sparse image won't be built until the end of next week (due to this change: https://github.com/AsteroidOS/meta-smartwatch/commit/26df07303fd30a13dac145c9e2faedd2d94afdb2).
> mooneye: Add permanent install

- pages/watches/koi.md
...and guide users to the matrix chat for step by step individual help to prevent bricking issues.
Given the recent koi bricks, possibly from user confusion with our install instructions, this PR temporarily removes the install instructions and redirects users to seek individual step by step guidance in the matrix chat.
The PR also adds a link to my WSD Fxx docks on Printables.com
> Temporarily block koi self service 

- pages/watches/beluga.md
explaining the partial usb support and missing SSH connection.
> Add USB info box to beluga install
